### ISSUE TITLE
OSError: Can't load tokenizer for 'gpt2'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'gpt2' is the correct path to a directory containing all relevant files for a GPT2TokenizerFast tokenizer.

### ISSUE THREAD

**Issue by 2741913295** [sceneteller/SceneTeller#3]
Dear Developer's ,

I hope this message finds you well. I am currently working with the SceneTeller project and encountered an issue while running the script run_layoutgen_3d_generateprompt.py in the SceneTeller/LayoutGen directory. I would appreciate your assistance in resolving this issue.

**Command:**

_python run_layoutgen_3d_generateprompt.py --dataset_dir ../scene_data/data_output/bedroom --room bedroom --gpt_type gpt4 --unit px --regular_floor_plan --generate_train --base_output_dir ./llm_output/bedroom-train-prompt_

**Error Message:**
The script fails with the following error message:

_/home/xw/anaconda3/envs/sceneteller/lib/python3.8/site-packages/huggingface_hub/file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "run_layoutgen_3d_generateprompt.py", line 16, in <module>
    tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")
  File "/home/xw/anaconda3/envs/sceneteller/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1809, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'gpt2'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'gpt2' is the correct path to a directory containing all relevant files for a GPT2TokenizerFast tokenizer._
**Issue:**
The error message indicates that the script is unable to load the GPT-2 tokenizer using the following line of code:

_tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")_

This seems to be caused by either an issue with downloading the model from Hugging Face or a conflict with a local directory named gpt2.

**Steps Taken:**
I verified that my network connection is stable, but the error persists.
I also checked for a local gpt2 directory in my working directory to ensure there is no conflict, but I couldn't find any such directory.
**Request:**
Could you kindly assist in resolving this issue? I would appreciate any guidance on how to fix this error, such as ensuring that the tokenizer is properly downloaded or troubleshooting any potential conflicts.

Thank you for your time and support.

**Comment by 2741913295** [comment]
**huggingface-cli download gpt2**
use this code can solve the problem
